primerProyecto/ejemplo_django/urls.py
from . import views
from django.urls import path

app_name = 'ejemplo_django'

urlpatterns = [
    path('',views.index,name='index'),
    path('ingreso',views.ingreso,name='ingreso'),
    path('sumador',views.sumador,name='sumador'),
]

primerProyecto/primerProyecto/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ejemplo_django/',include('ejemplo_django.urls')),
    path('proyCurso/',include('proyCurso.urls')),
    path('examenFinal/',include('examenFinal.urls')),
]

primerProyecto/proyCurso/urls.py
from . import views
from django.urls import path

app_name='proyCurso'

urlpatterns = [
    path('dashboard',views.dashboard,name='dashboard'),
    path('vistaProd/<str:ind>',views.vistaProd,name='vistaProd'),
    path('eliminarProd/<str:ind>',views.eliminarProd,name='eliminarProd'),
    path('obtenerInfo',views.obtenerInfo,name='obtenerInfo'),
    path('verSolicitudes',views.verSolicitudes,name='verSolicitudes'),
    path('crearSolicitud',views.crearSolicitud,name='crearSolicitud'),
    path('agregarSolicitud',views.agregarSolicitud,name='agregarSolicitud'),
    path('descargar_solicitud/<str:ind>',views.descargar_solicitud,name='descargar_solicitud'),
]

primerProyecto/ejemplo_django/models.py
from django.db import models

# Create your models here.
class usuariosDjango(models.Model):
    nombre = models.CharField(max_length=64,default='')
    apellido = models.CharField(max_length=64,default='')
    edad = models.CharField(max_length=64,default='')

class autos(models.Model):
    marca = models.CharField(max_length=128,default='')
    modelo = models.CharField(max_length=96,default='')
    kilometraje = models.CharField(max_length=32,default='')
    precio = models.CharField(max_length=32,default='')

primerProyecto/ejemplo_django/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import usuariosDjango

# Create your views here.
def index(request):
    return HttpResponse('Esta es mi primera vista')

def ingreso(request):
    usuariosInformacion = usuariosDjango.objects.all().order_by('id')
    if request.method == 'POST':
        if 'Crear' in request.POST:
            nuevoUsuario = []
            print('Hola, se ha posteado informacion')
            nombre = request.POST.get('nombreUsuario')
            apellido = request.POST.get('apellidoUsuario')
            edad = request.POST.get('edadUsuario')
            print('El nombre del usuario es : ' + str(nombre))
            print('El apellido del usuario es : ' + str(apellido))
            print('La edad del usuario es : ' + str(edad))
            nuevoUsuario.append(str(nombre))
            nuevoUsuario.append(str(apellido))
            nuevoUsuario.append(str(edad))
            usuariosDjango(nombre=str(nombre),apellido=str(apellido),edad=str(edad)).save()
            usuariosInformacion = usuariosDjango.objects.all().order_by('id')
        elif 'Filtrar' in request.POST:
            filtradoEdad = request.POST.get('edadFiltrado')
            usuariosInformacion = usuariosDjango.objects.filter(edad=filtradoEdad)
    return render(request,'ejemplo_django/ingreso.html',{
        'usuarios':usuariosInformacion,
    })

def sumador(request):
    return render(request,'ejemplo_django/sumador.html')

#Wappalyzer

primerProyecto/ejemplo_django/templates/ejemplo_django/ingreso.html
<!DOCTYPE html>
<html>
    <head>
        <title>Mi primer proyecto</title>
    </head>
    <body>
        <h2>Usuarios del proyecto Django</h2>
        <br>
        <form method="post" url="{% url 'ejemplo_django:ingreso' %}">
        {% csrf_token %}
            <select name="edadFiltrado">
                <option value="25">25</option>
                <option value="35">35</option>
            </select>
            <button type="submit" name="Filtrar">Filtrar</button>
        </form>
        <br>
        <button><a href="{% url 'ejemplo_django:ingreso' %}">Reestablecer</a></button>
        <br>
        {% for usuario in usuarios %}
        <h4>Nombre : {{ usuario.nombre }}</h4>
        <h4>Apellido : {{ usuario.apellido }}</h4>
        <h4>Edad : {{ usuario.edad }}</h4>
        <br>
        {% endfor %}
        <br>
        <h4>Ingrese nuevo usuario</h4>
        <form method="post" action="{% url 'ejemplo_django:ingreso' %}">
        {% csrf_token %}
            <div>
                <h4>Ingrese el nombre :</h4>
                <input type="text" name="nombreUsuario">
            </div>
            <div>
                <h4>Ingrese el apellido</h4>
                <input type="text" name="apellidoUsuario">
            </div>
            <div>
                <h4>Ingrese la edad</h4>
                <input type="number" name="edadUsuario">
            </div>
            <br>
            <button type="submit" name="Crear">Registrar usuario</button>
        </form>
    </body>
</html>

primerProyecto/ejemplo_django/templates/ejemplo_django/sumador.html
<!DOCTYPE html>
<html>
    <head>
        <title>React ejempklo</title>
        <script src="https://unpkg.com/react@18/umd/react.production.min.js" crossorigin></script>
        <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js" crossorigin></script>
        <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
    </head>
    <body>
        <div id="app"></div>
        <script type="text/babel">
            function App(){
                const [state,setState] = React.useState({
                    numero1 : 1,
                    numero2 : 1,
                    puntuacion:0,
                    respuesta:"",
                })

                function inputKeyPress(event)
                {
                    if(event.key === "Enter")
                    {
                        const resultado = parseInt(state.respuesta)
                        if(resultado === state.numero1 + state.numero2)
                        {
                            setState({
                                ...state,
                                numero1:Math.ceil(Math.random()*10),
                                numero2:Math.ceil(Math.random()*10),
                                puntuacion: state.puntuacion + 1
                            })
                        }
                    }
                }

                function actualizarRespuesta(event)
                {
                    setState({
                        ...state,
                        respuesta:event.target.value
                    })
                }

                function problema()
                {
                    return(
                        <div>
                            <div>
                                {state.numero1} + {state.numero2}
                            </div>
                            <input onKeyPress={inputKeyPress} onChange={actualizarRespuesta}/>
                            <div>Puntuacion : {state.puntuacion}</div>
                        </div>
                    );
                }
                return problema()
            }
            ReactDOM.render(<App/>,document.getElementById('app'))
        </script>
    </body>
</html>