primerProyecto/primerProyecto/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ejemplo_django/',include('ejemplo_django.urls')),
    path('proyCurso/',include('proyCurso.urls')),
    path('examenFinal/',include('examenFinal.urls')),
]

primerProyecto/proyCurso/urls.py
from . import views
from django.urls import path

app_name='proyCurso'

urlpatterns = [
    path('dashboard',views.dashboard,name='dashboard'),
    path('vistaProd/<str:ind>',views.vistaProd,name='vistaProd'),
    path('eliminarProd/<str:ind>',views.eliminarProd,name='eliminarProd'),
    path('obtenerInfo',views.obtenerInfo,name='obtenerInfo'),
    path('verSolicitudes',views.verSolicitudes,name='verSolicitudes'),
    path('crearSolicitud',views.crearSolicitud,name='crearSolicitud'),
    path('agregarSolicitud',views.agregarSolicitud,name='agregarSolicitud'),
    path('descargar_solicitud/<str:ind>',views.descargar_solicitud,name='descargar_solicitud'),
]

primerProyecto/proyCurso/models.py
from django.db import models
import datetime

# Create your models here.
class producto(models.Model):
    nombre = models.CharField(max_length=64,default='')
    precio = models.CharField(max_length=32,default='')
    nombreImagen = models.CharField(max_length=64,default='')
    descripcion = models.CharField(max_length=512,default='')
    estado = models.CharField(max_length=64,default='')
    stock = models.CharField(max_length=32,default='')

class solicitud(models.Model):
    idProductos = models.CharField(max_length=256,default='')
    nombreProductos = models.CharField(max_length=512,default='')
    cantidadProductos = models.CharField(max_length=512,default='')
    fecha = models.DateField(default=datetime.datetime.now())
    cliente = models.CharField(max_length=128,default='Cliente')
    codigoSolicitud = models.CharField(max_length=128,default='SOL-0000')

primerProyecto/proyCurso/views.py
from django.shortcuts import render
from .models import producto,solicitud
from django.http import HttpResponseRedirect,JsonResponse, HttpResponse
from django.urls import reverse
import json
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4

# Create your views here.
def descargar_solicitud(request,ind):
    solicitu_info = solicitud.objects.get(id=ind)
    pdf_name = 'solicitud.pdf'
    can = canvas.Canvas(pdf_name,pagesize=A4)
    can.setFillColorRGB(0,0,0)
    can.setFont('Helvetica',12)
    can.drawString(20,785,solicitu_info.codigoSolicitud)
    infoProductos = solicitu_info.nombreProductos.split(',')
    infoCantidad = solicitu_info.cantidadProductos.split(',')
    i= 0
    coor_y = 750
    for producto in infoProductos:
        can.drawString(20,coor_y,producto)
        can.drawString(120,coor_y,infoCantidad[i])
        coor_y = coor_y - 20
        i = i + 1
    can.showPage()
    can.save()
    nombre_doc = solicitu_info.codigoSolicitud + '.pdf'
    reponse = HttpResponse(open('solicitud.pdf','rb'),content_type='application/pdf')
    nombre = 'attachment; + filename=' + nombre_doc
    reponse['Content-Disposition'] = nombre
    return reponse

def dashboard(request):
    productos_totales = producto.objects.all()
    return render(request,'proyCurso/dashboard.html',{
        'productos_totales':productos_totales
    })

def vistaProd(request,ind):
    producto_seleccionado = producto.objects.get(id=ind)
    return render(request,'proyCurso/vistaProd.html',{
        'producto_seleccionado':producto_seleccionado
    })

def eliminarProd(request,ind):
    producto_eliminar = producto.objects.get(id=ind)
    producto_eliminar.delete()
    return HttpResponseRedirect(reverse('proyCurso:dashboard'))

def obtenerInfo(request):
    datoProducto = str(request.GET.get('producto'))
    infoProducto = producto.objects.get(id=datoProducto)
    arregloProducto = [infoProducto.id,infoProducto.nombre,infoProducto.precio,infoProducto.descripcion,infoProducto.estado,infoProducto.stock]
    return JsonResponse({
        'dato':arregloProducto,
    })

def verSolicitudes(request):
    solicitudesTotales = solicitud.objects.all().order_by('-id')
    return render(request,'proyCurso/verSolicitudes.html',{
        'solicitudes':solicitudesTotales,
    })

def crearSolicitud(request):
    productos_totales = producto.objects.all().order_by('id')
    return render(request,'proyCurso/crearSolicitud.html',{
        'productos':productos_totales
    })

def agregarSolicitud(request):
    if request.method == 'POST':
        datos = json.load(request)
        arregloProductos = datos.get('productosCapturados')
        cliente = datos.get('cliente')
        print(arregloProductos)
        nombresProductos = ''
        cantidadesProductos = ''
        idenProductos = ''
        for producto in arregloProductos:
            idenProductos = idenProductos + ',' + producto[0]
            nombresProductos = nombresProductos + ',' + producto[1]
            cantidadesProductos = cantidadesProductos + ',' + producto[2]
        nombresProductos = nombresProductos[1:]
        cantidadesProductos = cantidadesProductos[1:]
        idenProductos = idenProductos[1:]
        solicitud(idProductos=idenProductos,nombreProductos=nombresProductos,cantidadProductos=cantidadesProductos,cliente=cliente).save()
        print(nombresProductos)
        print(cantidadesProductos)
        print(idenProductos)
        solicitud_mod = solicitud.objects.latest('id')
        id_solicitud = str(solicitud_mod.id)
        while len(id_solicitud) < 4:
            id_solicitud = '0' + id_solicitud
        solicitud_mod.codigoSolicitud = 'SOL-' + id_solicitud
        solicitud_mod.save()
        return JsonResponse({
            'resp':'ok'
        })

primerProyecto/proyCurso/templates/proyCurso/crearSolicitud.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Crear solicitud</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
        <script src="{% static 'proyCurso/crearSol.js' %}"></script>
    </head>
    <body>
        <div class="container">
            <div class="alert alert-success text-center">
                <h2>Crear solicitud</h2>
            </div>
            <br>
            <div class="row">
                <div class="col-3">
                    <select class="form-select" id="infoProducto">
                        <option value=""></option>
                        {% for producto in productos %}
                        <option value="{{ producto.id }}">{{ producto.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-2">
                    <button class="btn btn-success" onclick="agregarProducto()">Agregar</button>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-3">
                    <label class="form-label">Cliente :</label>
                    <input class="form-control" id="clienteSolicitud">
                </div>
            </div>
            <div class="row">
                <div class="col-1">
                    <label class="form-label">ID :</label>
                    <input class="form-control" readonly id="idProducto">
                </div>
                <div class="col-2">
                    <label class="form-label">Nombre :</label>
                    <input class="form-control" readonly id="nombreProducto">
                </div>
                <div class="col-3">
                    <label class="form-label">Estado :</label>
                    <input class="form-control" readonly id="estadoProducto">
                </div>
                <div class="col-3">
                    <label class="form-label">Precio :</label>
                    <input class="form-control" readonly id="precioProducto">
                </div>
                <div class="col-3">
                    <label class="form-label">Cantidad :</label>
                    <input class="form-control" type="number" id="cantidadProducto">
                </div>
            </div>
            <br>
            <div class="row justify-content-center">
                <table class="table table-bordered">
                    <thead class="table-dark">
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Cantidad</th>
                        <th>Estado</th>
                        <th>Precio</th>
                    </thead>
                    <tbody id="cuerpoTabla">
                    </tbody>
                </table>
            </div>
            <div class="row">
                <div class="col-10">

                </div>
                <div class="col-1">
                    <button class="btn btn-primary" onclick="crearSolicitud()">Crear</button>
                </div>
                <div class="col-1">
                    <a class="btn btn-info" href="{% url 'proyCurso:dashboard' %}">Cancelar</a>
                </div>
            </div>
        </div>
    </body>
</html>

primerProyecto/proyCurso/templates/proyCurso/dashboard.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Dashboard del proyecto</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
        <script src="{% static 'proyCurso/dashboard.js' %}"></script>
    </head>
    <body>
        <div class="container">
            <br>
            <div id="anuncio"></div>
            <div class="row alert alert-danger text-center">
                <h3>Figuras de coleccion</h3>
            </div>
            <div class="row">
                <div class="col-10"></div>
                <div class="col-2">
                    <a class="btn btn-success" href="{% url 'proyCurso:verSolicitudes' %}">Solicitudes</a>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-6 bg-white">
                    {% for producto in productos_totales %}
                    <div class="row bg-light justify-content-center" style="border-radius: 3px; border-bottom: solid 1px black;">
                        <br>
                        <div class="row justify-content-center">
                            <div class="col-8 alert alert-success text-center">
                                <h5 class="nombreProducto" id="{{ producto.id }}">{{ producto.nombre }}</h5>
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <div class="col-4">
                                <img src="{% static producto.nombreImagen %}" height="240px">
                            </div>
                            <div class="col-6">
                                <br>
                                <div class="row">
                                    <h4>Precio : {{ producto.precio }}</h4>
                                </div>
                                <br>
                                <div class="row">
                                    <h6>Stock: {{ producto.stock }}</h6>
                                </div>
                                <br>
                                <div class="row">
                                    <a class="btn btn-success" data-bs-toggle="modal" data-bs-target="#verProducto" onclick="obtenerInfo(this.id)" id="{{ producto.id }}">Ver producto</a>
                                </div>
                                <div class="row" style="display: none;">
                                    <a class="btn btn-danger" href="{% url 'proyCurso:eliminarProd' producto.id %}">Eliminar Producto</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                    {% endfor %}
                    <!--
                    <div class="row" id="ejemploJS">
                        <button onclick="f1()">Click Here</button>
                    </div>
                    <div class="row">
                        <h1>Seleccione estado</h1>
                        <select class="form-select" onchange="f2()">
                            <option selected></option>
                            <option value="Nuevo">Nuevo</option>
                            <option value="Abierto">Abierto</option>
                        </select>
                    </div>-->
                </div>
            </div>
        </div>

        <div class="modal fade" tabindex="-1" role="dialog" id="verProducto">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="tituloProducto">Modal title</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" id="infoProducto">
                        <table class="table table-bordered">
                            <thead class="table-dark">
                                <th>Caracteristica</th>
                                <th>Valor</th>
                            </thead>
                            <tbody id="cuerpoTabla">
                            </tbody>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Save changes</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

primerProyecto/proyCurso/templates/proyCurso/verSolicitudes.html
<!DOCTYPE html>
<html>
    <head>
        <title>Lista de solicitudes de compra</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            <div class="alert alert-success text-center">
                <h2>Solicitudes de compra</h2>
            </div>
            <br>
            <div class="row">
                <div class="col-2">
                    <a class="btn btn-success" href="{% url 'proyCurso:crearSolicitud' %}">Crear solicitud</a>
                </div>
                <div class="col-8">

                </div>
                <div class="col-2">
                    <a class="btn btn-info" href="{% url 'proyCurso:dashboard' %}">Volver</a>
                </div>
            </div>
            <br>
            <div class="row">
                <table class="table table-bordered">
                    <thead class="table-dark">
                        <th>Id</th>
                        <th>Fecha</th>
                        <th>Cliente</th>
                        <th>Codigo de solicitud</th>
                        <th>Descargar</th>
                    </thead>
                    <tbody>
                        {% for solicitud in solicitudes %}
                        <tr>
                            <td>{{ solicitud.id }}</td>
                            <td>{{ solicitud.fecha|date:'d-m-Y' }}</td>
                            <td>{{ solicitud.cliente }}</td>
                            <td>{{ solicitud.codigoSolicitud }}</td>
                            <td><a class="btn btn-info" href="{% url 'proyCurso:descargar_solicitud' solicitud.id %}">Descargar</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>

primerProyecto/proyCurso/templates/proyCurso/vistaProd.html
<!DOCTYPE html>
<html>
    <head>
        <title>Vista de producto</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            <div class="row text-center">
                {{ producto_seleccionado.nombre }}
            </div>
            <div class="row text-center">
                {{ producto_seleccionado.descripcion }}
            </div>
            <div class="row text-center">
                {{ producto_seleccionado.stock }}
            </div>
            <div class="row text-center">
                {{ producto_seleccionado.precio }}
            </div>
            <div class="row text-center">
                {{ producto_seleccionado.estado }}
            </div>
        </div>
    </body>
</html>