primerProyecto/examenFinal/urls.py
from . import views
from django.urls import path

app_name = 'examenFinal'

urlpatterns = [
    path('',views.index,name='index'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('obtener_info_tarea', views.obtener_info_tarea, name='obtener_info_tarea'),
    path('crear_tarea', views.crear_tarea, name='crear_tarea'),
    path('eliminar_tarea', views.eliminar_tarea,name = 'eliminar_tarea'),
    path('editar_tarea', views.editar_tarea, name='editar_tarea'),
]

primerProyecto/primerProyecto/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ejemplo_django/',include('ejemplo_django.urls')),
    path('proyCurso/',include('proyCurso.urls')),
    path('examenFinal/',include('examenFinal.urls')),
]

primerProyecto/proyCurso/urls.py
from . import views
from django.urls import path

app_name='proyCurso'

urlpatterns = [
    path('dashboard',views.dashboard,name='dashboard'),
    path('vistaProd/<str:ind>',views.vistaProd,name='vistaProd'),
    path('eliminarProd/<str:ind>',views.eliminarProd,name='eliminarProd'),
    path('obtenerInfo',views.obtenerInfo,name='obtenerInfo'),
    path('verSolicitudes',views.verSolicitudes,name='verSolicitudes'),
    path('crearSolicitud',views.crearSolicitud,name='crearSolicitud'),
    path('agregarSolicitud',views.agregarSolicitud,name='agregarSolicitud'),
    path('descargar_solicitud/<str:ind>',views.descargar_solicitud,name='descargar_solicitud'),
]

primerProyecto/examenFinal/models.py
from django.db import models

# Create your models here.
class usuariosFinal(models.Model):
    usuario = models.CharField(max_length=256,default='')
    contra = models.CharField(max_length=256,default='')

class tareasExamen(models.Model):
    fechaCreacion = models.CharField(max_length=256,default='24-09-2022')
    fechaEntrega = models.CharField(max_length=256,default='30-09-2022')
    descripcion = models.CharField(max_length=512,default='')
    estadoTarea = models.CharField(max_length=128,default='PROGRESO')

primerProyecto/examenFinal/views.py
from django.shortcuts import render
from django.urls import reverse
from .models import tareasExamen, usuariosFinal
from django.http import HttpResponse,HttpResponseRedirect, JsonResponse
import json

# Create your views here.
def index(request):
    if request.method == 'POST':
        nombreUsuario = request.POST.get('nombreUsuario')
        passwordUsuario = request.POST.get('passwordUsuario')
        #Validacion de informacion
        usuario_registrado = 0
        usuarios_totales = usuariosFinal.objects.all()

        for usuario in usuarios_totales:
            if usuario.usuario == nombreUsuario and usuario.contra == passwordUsuario:
                usuario_registrado = 1
        
        if usuario_registrado == 1:
            return HttpResponseRedirect(reverse('examenFinal:dashboard'))
        else:
            return render(request,'examenFinal/ingresar.html',{
                'mensaje':'Los datos ingresados son incorrectos',
            })
    return render(request,'examenFinal/ingresar.html')

def dashboard(request):
    return render(request,'examenFinal/dashboard.html',{
        'tareas_totales':tareasExamen.objects.all().order_by('id')
    })
#Obtengo la información de la tarea
def obtener_info_tarea(request):
    datoTarea = str(request.GET.get('tarea')) #obtengo el identificador
    infoTarea = tareasExamen.objects.get(id=datoTarea) #obtengo la info de la tarea seleccionada
    arregloTarea = [infoTarea.fechaCreacion, infoTarea.fechaEntrega, infoTarea.descripcion, infoTarea.estadoTarea] #coloco la información en un arreglo
    print(datoTarea)

    return JsonResponse({
        'dato': arregloTarea, # paso los datos de la tarea seleccionada a la parte front
    })
def crear_tarea(request):
    if request.method == 'POST':
        datos = json.load(request) #Recepciono los datos en formato JSON
        arregloTarea = datos.get('TareaCapturada') # Obtengo el arreglo
        tareasExamen(fechaCreacion = arregloTarea[0], fechaEntrega = arregloTarea[1], descripcion = arregloTarea[2], estadoTarea = arregloTarea[3]).save() # lo guardo en la base de datos
        print(arregloTarea)
        return JsonResponse({
            'resp':'ok'
        })
def eliminar_tarea(request):
    idtarea = str(request.GET.get('tarea')) #obtengo el id de la tarea
    Tarea_eliminar = tareasExamen.objects.get(id=idtarea) #Obtengo la info de la tarea seleccionada
    Tarea_eliminar.delete()# Elimino la tarea de la base de datos
    return JsonResponse({
            'resp':'ok'
        })

def editar_tarea(request):
    datoTarea = str(request.GET.get('tarea')) #obtengo el identificador
    infoTarea = tareasExamen.objects.get(id=datoTarea) #obtengo la info de la tarea seleccionada
    arregloTarea = [infoTarea.fechaCreacion, infoTarea.fechaEntrega, infoTarea.descripcion, infoTarea.estadoTarea] #coloco la información en un arreglo
    print(datoTarea)

    return JsonResponse({
        'dato': arregloTarea, # paso los datos de la tarea seleccionada a la parte front
    })

primerProyecto/examenFinal/templates/examenFinal/ingresar.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Ingresar</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    </head>
    <body>
        <section class="vh-100 bg-primary" >
            <div class="container py-5 h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                        <div class="card shadow-2-strong" style="border-radius: 1rem;">
                            <div class="card-body p-5 text-center">
                                <h3 class="mb-5">Ingrese a su cuenta</h3>
                                <form action="{% url 'examenFinal:index' %}" method="post">
                                {% csrf_token %}
                                    <div class="form-outline mb-4">
                                        <input type="user" name="nombreUsuario" placeholder="Usuario" class="form-control form-control-lg" />
                                    </div>
                                    <div class="form-outline mb-4">
                                        <input type="password" name="passwordUsuario" placeholder="Contraseña" class="form-control form-control-lg" />
                                    </div>
                                    <div>
                                        <button class="btn btn-primary btn-lg btn-block" type="submit">Ingresar</button>
                                    </div>
                                    {% if message %}
                                    <div>
                                        {{ message }}
                                    </div>
                                    {% endif %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>